swagger: "2.0"
info:
  title: FreeMontors
  description: FreeMentors
  version: 1.0.0
host: localhost:3000
basePath: /app
schemes:
  - http
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK